// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // 마이그레이션 시에는 DIRECT_URL (Session Pooler 5432) 사용
    // 예: DATABASE_URL=$DIRECT_URL npx prisma migrate deploy
    url: process.env["DATABASE_URL"],
  },
});
