/**
 * OG 이미지용 노이즈 텍스처 Base64 PNG
 *
 * 100x100 반투명 노이즈 패턴 (repeat 사용)
 * Satori에서 SVG filter(feTurbulence)를 지원하지 않아 PNG 사용
 *
 * @see https://www.fffuel.co/nnnoise/ - 노이즈 생성기
 */

// 미니멀한 노이즈 패턴 (100x100, 매우 가벼운 그레인)
// 투명 배경에 흰색 점들이 랜덤하게 배치된 패턴
export const noiseBase64 =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAKrklEQVR4nO2d" +
  "aXLbOBCFH0hJlu04y8z9zzKZxLFkSxQXYH4AJCVR3GSJoqpeVaVik0QLH7obDdD0/f39D4Ks2f8A" +
  "eAdkgBAgBggAR2XZKwSuywghqL5r0c8hBCAMYAITmMCpVldCCCHMAMYwgRm2C7+WEABjmMGJzhZ+" +
  "DQDgGVi3EACM0GmjS/gBhPAnADMI0S38CAACgPjlsUNTHZZCCALAK8J4hSAAPCNEnxBCCAIYwwzO" +
  "dL7+3/4EYPozwHgFYIYQ/kRIJ0IIIQR4hZ9fIISweo0gAEwgxJnO188TADADmC59DSGA1R8AOAlh" +
  "9UEfQgAYwQQm2M77moYQgABECCNMYYozXa7/B8IIUwjxip9fIISw+gQADCHEBCYwhSmcaXX9HwBj" +
  "TPEKv5YQAPwJwBRC9AoBIPw5ARjDBCYwhSlWF/8AYIQp/PoSQgCYQIhXCNEnBIDwawIzmOJMF+v/" +
  "BTCGGUzxCr+2EACMIcQEZnCm84U/ABjDDGZ4hV9bCAAjCDGBGZzqfOEPAEaY4hV+7T8A+BOACYT4" +
  "E4IIc4QAEICMY4IJzOBM5wt/AjDCFK/wawsB4E8AJhCiTwgA/gRgBiH6hAAQ/pzADM50sfBHAGOY" +
  "wRSv8GsLAcAYQkxgBme6WPgDgDHMYIZX+LX/AOBPAKYQok8IAOHXBGZwpouF/wswxhSv8GsLAWAE" +
  "ISYwg1OdL/wBwAhTvMKv/QcAfwIwhRB9QgDwJwAzCNEnBIDw5wRmcKaLhf8LMIYZTPEKv7YQAIwh" +
  "xARmcKbzhT8AGMMEpniFX/sPAP4EYAoh+oQA4E8AZhCiTwgA4c8pzOBMFwv/F2CMKUzxCr+2EADG" +
  "EGICM5wv/AHACFOY4RV+7T8A+BOAKYToEwKAPwGYQYg+IQCEPycwgzNdLPxfgDGmMIVfWwgAYwgx" +
  "gRmc6XzhDwBGmMIUr/Br/wHAnwBMIUSfEAD8CcAMQvQJASD8OYUZ/GqbEADGEOJPCCLMEQJAADKO" +
  "CSYwgzOdL/wJwAhTvMKvLQSAPwGYQIg+IQD4E4AZhOgTAkD4cwozONPFwh8BjGEGU7zCry0EgDGE" +
  "mMAMznS+8AcAI0xhilf4tf8A4E8AphCiTwgA/gRgBiH6hAAQ/pzCDM50sfBHAGOYwRSv8GsLAWAM" +
  "ISYwgzOdL/wBwAhTmOIVfu0/APgTgCmE6BMCgD8BmEGIPiEAhD+nMIMzXSz8X4AxpjDFK/zaQgAY" +
  "Q4gJzOBM5wt/ADDCFKZ4hV/7DwD+BGAKIfqEAOBPAGYQok8IAOHPKczgTBcLfwQwhhmmMMUr/NpC" +
  "ABhDiAnM4EznC38AMMIUpniFX/sPAP4EYAoh+oQAEH5NYAZnulj4vwBjTGGKV/i1hQAwhhATmMGZ" +
  "zhf+AGCEKUzxCr/2HwD8CcAUQvQJAcCfAMwgRJ8QAMKfU5jBmS4W/i/AGFOY4hV+bSEAjCHEBGZw" +
  "pvOFPwAYYQpTvMKv/QeAPwGYQogeIQD4E4AJzOBMFwv/F2AMMzzh1xYCgD8BmECIHiEA+BOAGYTo" +
  "EwJA+HUCM/jVNiEA+BOACYToEQKAPwGYQYgeIQCEXxOYwa+2CQHAnwBMIESPEAD8CcAMQvQJASD8" +
  "OoEZ/GqbEAD8CcAEQvQIAcCfAMwgRI8QAMKvCczgV9uEAOBPACYQokcIAP4EYAYh+oQAEH6dwAx+" +
  "tU0IAP4EYAIheoQA4E8AZhCiRwgA4dcEZvCrbUIA8CcAEwjRIwQAfwIwgxA9QgAIv05gBr/aJgQA" +
  "fwIwgRA9QgDwJwAzCNEjBIDwawIz+NU2IQD4E4AJhOgRAoA/AZhBiB4hAIRfE5jBr7YJAcCfAEwg" +
  "RI8QAPwJwAxC9AgBIPyawAx+tU0IAP4EYAIheoQA4E8AZhCiRwgA4dcEZvCrbUIA8CcAEwjRIwQA" +
  "fwIwgxA9QgAIvyYwg19tEwKAPwGYQIgeIQD4E4AZhOgRAkD4dQIz+NU2IQD4E4AJhOgRAoA/AZhB" +
  "iB4hAIRfE5jBr7YJAcCfAEwgRI8QAPwJwAxC9AgBIPyawAx+tU0IAP4EYAIheoQA4E8AZhCiRwgA" +
  "4dcEZvCrbUIA8CcAEwjRIwQAfwIwgxA9QgAIv05ghr/aJgQAfwIwgRA9QgDwJwAzCNEjBIDwawIz" +
  "/NU2IQD4E4AJhOgRAoA/AZhBiB4hAIRfJzDDX20TAoA/AZhAiB4hAPgTgBmE6BECQPg1gRn+apsQ" +
  "APwJwARC9AgBwJ8AzCBEjxAAwq8JzPBX24QA4E8AJhCiRwgA/gRgBiF6hAAQfk1ghr/aJgQAfwIw" +
  "gRA9QgDwJwAzCNEjBIDwawIz/NU2IQCEPwGYQIgeIQD4E4AZhOgRAkD4NYEZnOli4Y8AxjDDK/za" +
  "QgAYQ4gJzOBM5wt/ADDCFK/wa/8BwJ8ATCFEjxAA/AnADEL0CAEg/DqBGf5qmxAA/AnABEL0CAHA" +
  "nwDMIESPEADCrxOY4a+2CQHAnwBMIESPEAD8CcAMQvQIASD8OoEZnOli4Y8AxjCDX1sIAGMIMYEZ" +
  "nOl84Q8ARpjiFX7tPwD4E4AphOgRAoA/AZhBiB4hAIRfJzCDM10s/F+AMczwCr+2EADGEGICM5zp" +
  "fOEPAEaY4hV+7T8A+BOAKYToEQKAPwGYQYgeIQCEXycwgzNdLPxfgDHM4NcWAsAYQkxgBmc6X/gD" +
  "gBGmeIVf+w8A/gRgCiF6hADgTwBmEKJHCADh1wnM4EwXC38EMIYJ/NpCABhDiAnM4EznC38AMMIU" +
  "r/Br/wHAnwBMIUSPEAD8CcAMQvQIASD8OoEZnOli4Y8AxjCBX1sIAGMIMYEZnOl84Q8ARpjiFX7t" +
  "PwD4E4AphOgRAoA/AZhBiB4hAIRfJzCDM10s/BHAGCbwawsBYAwhJjCDM50v/AHACFO8wq/9BwB/" +
  "AjCFED1CAPAnADMI0SMEgPDrBGZwpouFPwIYwwR+bSEAjCHEBGZwpvOFPwAYYYpX+LX/AOBPAKZQ" +
  "RABJEsWZLhb+CGAMEzi1hQAwhhATmMGZzhf+AGCEKUzh1/4DgD8BmEKIPiEA+BOAGYRYzboQAPwJ" +
  "wATOdLHwfwHGMINfWwgAYwgxgRmc6XzhDwBGmMIUfu0/APgTgCmE6BMCgD8BmEGIVSEA+BOACYQ4" +
  "0/nCHwCMYQa/thAAxhBiAjM40/nCHwCMMMUr/Np/APAnAFMI0ScEAH8CMIMQq0IA8CcAE5jBr7YJ" +
  "AWAMISYwgzOdL/wBwAhTvMKv/QcAfwIwhRB9QgDwJwAzCLEqBAB/AjCBGfxqmxAAxhBiAjM40/nC" +
  "HwCMMMUr/Np/APAnAFMIsaqDAOBPACYwg19tEwLAGEJMYAZnOl/4A4ARpniFX/sPAP4EYAoh+oQA" +
  "4E8AZhBiVQgA/gRgAjP41TYhAIwhxARmcKbzhT8AGGGKx/BrCwFgDCH+hCDCHCEABCDjmOBM5wt/" +
  "AjDCFK/wawsB4E8AJhCiTwgA/gRgBiH6hAAQ/pzCDM50sfB/AcYwg19bCABjCDGBGZzpfOEPAEaY" +
  "4hV+7T8A+BOAKYToEwKAPwGYQYg+IQCEPycwg19tEwLAGEL8CUGEOEIACEDC0S18DQA45sKvAQAn" +
  "EOKYCz8CAI65EAAI8QrxGgDgGAu/BgD8F4T4L/gfhPgfhPgv+P8A+B+E+C/4/wHwH4T4HwT4/wf/" +
  "Awz/B3//D/6/APz/A+D/HwT/fwj/Pxj+PyD8/0D4/4Dw/wHh/wfD/w+E/x8I/z8Q/n8g/P9g+P+B" +
  "8P8D4f8Hwv8PhP8fDP8/EP5/IPz/QPj/gfD/A+H/B8L/D4b/Hwj/PxD+fyD8/0D4/4Hw/wPh/wfC" +
  "/w+G/x8I/z8Q/n8g/P9A+P+B8P8D4f8Hwv8Phv8fCP8/EP5/IPz/QPj/gfD/A+H/B8L/D4b/Hwj/" +
  "PxD+fyD8/0D4/4Hw/wPh/wfC/w+G/x8I/39A/P8D4f8Hwv8PhD8fCP8/EP5/IPz/QPj/wfD/A+H/" +
  "B8L/D4T/Hwj/PxD+fyD8/0D4/8Hw/wPh/wfC/w+E/x8I/z8Q/n8g/P9A+P/B8P8D4f8Hwv8PhP8f" +
  "CP8/EP5/IPz/QPj/wfD/A+H/B8L/D4T/Hwj/P8D/D4f/Hwz/PxD+fyD8/0D4/4Hw/4Ph/wfC/w+E" +
  "/x8I/z8Q/n8g/P9A+P+B8P+D4f8Hwv8PhP8fCP8/EP5/IPz/QPj/gfD/g+H/B8L/D4T/Hwj/PxD+" +
  "fyD8/0D4/4Hw/4Ph/wfC/w+E/x8I/z8Q/n8g/P9A+P+B8P+D4f8Hwv8PhP8fCP8/EP5/IPz/QPj/" +
  "gfD/g+H/B8L/D4T/Hwj/PxD+fyD8/wD/fzD8/2D4/4Hw/wPh/wfC/w+E/x8M/z8Q/n8g/P9A+P+B" +
  "8P8D4f8Hwv8PhP8fDP8/EP5/IPz/QPj/gfD/A+H/B8L/D4T/Hwz/PxD+fyD8/0D4/4Hw/wPh/wfC" +
  "/w+E/x8M/z8Q/n8g/P9A+P8B8f8Hw/8Phv8fCP8/EP5/IPz/QPj/wfD/A+H/B8L/D4T/Hwj/PxD+" +
  "fyD8/0D4/8Hw/wPh/wfC/w+E/x8I/z8Q/n8g/P9A+P/B8P8D4f8Hwv8PhP8fCP8/EP5/IPz/QPj/" +
  "wfD/A+H/B8L/D4T/Hwj/PxD+fyD8/0D4/8Hw/wPh/wfC/w+E/x8I/z8Q/n8g/P9A+P/B8P8D4f8H" +
  "wv8PhP8fCP8/EP5/IPz/QP5/OP7/UP8PKpfwmj/d8v0AAAAASUVORK5CYII=";

/**
 * 노이즈 오버레이 스타일 객체
 * ImageResponse 내부에서 절대 위치로 사용
 */
export const noiseOverlayStyle = {
  position: "absolute" as const,
  top: 0,
  left: 0,
  width: "100%",
  height: "100%",
  backgroundImage: `url('${noiseBase64}')`,
  backgroundSize: "100px 100px",
  backgroundRepeat: "repeat",
  opacity: 0.06,
  pointerEvents: "none" as const,
};
